#!/bin/sh

umask g-w,o-w

# Oh My Zsh
if [ ! -d ~/.oh-my-zsh ]
then
    git clone -c core.eol=lf -c core.autocrlf=false \
        -c fsck.zeroPaddedFilemode=ignore \
        -c fetch.fsck.zeroPaddedFilemode=ignore \
        -c receive.fsck.zeroPaddedFilemode=ignore \
        --depth=1 --branch master \
        https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
fi

# tmux plugins
mkdir -p ~/.tmux/plugins

if [ ! -d ~/.tmux/plugins/tpm ]
then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [ -x ~/.tmux/plugins/tpm/bin/install_plugins ]
then
    ~/.tmux/plugins/tpm/bin/install_plugins
fi

if [ -x ~/.tmux/plugins/tpm/bin/update_plugins ]
then
    ~/.tmux/plugins/tpm/bin/update_plugins all
fi

# Nerd Fonts
mkdir -p ~/.local/share/fonts
cd ~/.local/share/fonts

rm Hack*.ttf
base_url=https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack
for var in Bold BoldItalic Italic Regular
do
    curl -sSfLo "HackNerdFont-$var.ttf" "$base_url/$var/HackNerdFont-$var.ttf"
done

curl -sSfLo fontawesome.zip https://use.fontawesome.com/releases/v6.4.0/fontawesome-free-6.4.0-desktop.zip
unzip -oj fontawesome.zip 'fontawesome-free-6.4.0-desktop/otfs/*' -d .
rm fontawesome.zip

cd -
