#!/bin/sh

umask g-w,o-w

if [ ! -d ~/.oh-my-zsh ]
then
    git clone -c core.eol=lf -c core.autocrlf=false \
        -c fsck.zeroPaddedFilemode=ignore \
        -c fetch.fsck.zeroPaddedFilemode=ignore \
        -c receive.fsck.zeroPaddedFilemode=ignore \
        --depth=1 --branch master \
        https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
fi

mkdir -p ~/.tmux/plugins

if [ ! -d ~/.tmux/plugins/tpm ]
then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [ -x ~/.tmux/plugins/tpm/bin/install_plugins ]
then
    ~/.tmux/plugins/tpm/bin/install_plugins
fi

if [ -x ~/.tmux/plugins/tpm/bin/update_plugins ]
then
    ~/.tmux/plugins/tpm/bin/update_plugins all
fi
