#!/usr/bin/bash

######################
## GENERAL SETTINGS ##
######################

riverctl keyboard-layout br
riverctl hide-cursor timeout 2000
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl set-repeat 35 300      # keyboard repeat rate


################
## APPEARANCE ##
################

riverctl border-width 4
riverctl border-color-focused 0x00aaff
riverctl border-color-unfocused 0x444444


################
## MEDIA KEYS ##
################

for mode in normal locked
do
    # Volume
    riverctl map $mode None  XF86AudioMute         spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"
    riverctl map $mode None  XF86AudioRaiseVolume  spawn "pactl set-sink-volume @DEFAULT_SINK@ +5%"
    riverctl map $mode None  XF86AudioLowerVolume  spawn "pactl set-sink-volume @DEFAULT_SINK@ -5%"
    riverctl map $mode Super Up                    spawn "pactl set-sink-volume @DEFAULT_SINK@ +5%"
    riverctl map $mode Super Down                  spawn "pactl set-sink-volume @DEFAULT_SINK@ -5%"

    # Media players
    riverctl map $mode None  XF86AudioMedia        spawn "playerctl play-pause"
    riverctl map $mode None  XF86AudioPlay         spawn "playerctl play-pause"
    riverctl map $mode None  XF86AudioPause        spawn "playerctl play-pause"
    riverctl map $mode None  XF86AudioPrev         spawn "playerctl previous"
    riverctl map $mode None  XF86AudioNext         spawn "playerctl next"
    riverctl map $mode Super Space                 spawn "playerctl play-pause"
    riverctl map $mode Super Left                  spawn "playerctl previous"
    riverctl map $mode Super Right                 spawn "playerctl next"
done


##################
## KEY MAPPINGS ##
##################

riverctl map normal Super       Q     close
riverctl map normal Super       J     focus-view next
riverctl map normal Super       K     focus-view previous
riverctl map normal Super+Shift J     swap next
riverctl map normal Super+Shift K     swap previous
riverctl map normal Super+Shift Space toggle-float

riverctl map normal Control+Alt Delete    spawn "echo -e 'poweroff\nreboot' | fuzzel -d -l 2 -w 20 | xargs -r systemctl"
riverctl map normal Super+Shift BackSpace spawn "loginctl lock-session"
riverctl map normal Super       Return    spawn "fuzzel"
riverctl map normal None        Print     spawn "slurp | grim -g - - | swappy -f -"


######################
## POINTER MAPPINGS ##
######################

riverctl map-pointer normal Super BTN_LEFT   move-view
riverctl map-pointer normal Super BTN_RIGHT  resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float


####################
## TAG MANAGEMENT ##
####################

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super               $i set-focused-tags $tags
    riverctl map normal Super+Shift         $i set-view-tags $tags
    riverctl map normal Super+Control       $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super       0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags


############
## LAYOUT ##
############

riverctl default-layout rivertile
riverctl spawn "rivertile -view-padding 6 -outer-padding 6 -main-location right -main-ratio 0.55"

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl declare-mode layout
riverctl map normal Super A enter-mode layout
riverctl map layout Super A enter-mode normal
riverctl map layout None  W send-layout-cmd rivertile "main-location top"
riverctl map layout None  A send-layout-cmd rivertile "main-location left"
riverctl map layout None  S send-layout-cmd rivertile "main-location bottom"
riverctl map layout None  D send-layout-cmd rivertile "main-location right"


###########
## RULES ##
###########

riverctl rule-add -app-id blueman-manager       float
riverctl rule-add -app-id pavucontrol           float
riverctl rule-add -app-id nm-connection-editor  float
riverctl rule-add -app-id galculator            float
riverctl rule-add -app-id org.mozilla.firefox   ssd
riverctl rule-add -title  Picture-in-Picture    float
riverctl rule-add -app-id Spotify               tags $((1 << 8))


#################
## ENVIRONMENT ##
#################

systemctl --user import-environment DISPLAY WAYLAND_DISPLAY
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY


###############
## AUTOSTART ##
###############

riverctl spawn "xss-lock -- swaylock -i $HOME/.config/river/wallpaper-lock --indicator-y-position=2000"
riverctl spawn "swaybg -i $HOME/.config/river/wallpaper"
riverctl spawn "mako"
riverctl spawn "yambar"
riverctl spawn "nextcloud --background"
