[font]
size = 9

[font.normal]
family = "Hack Nerd Font"

[shell]
program = "/usr/bin/tmux"
args = ["new", "-A"]

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "NumpadEnter"

[mouse]
hide_when_typing = true

# Colors from darker variant of onedark vim theme
# background modified to match my modified bg0 color
# https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/palette.lua
[colors.primary]
background = "#1e2127"
foreground = "#a0a8b7"

[colors.normal]
black = "#535965"
blue = "#4fa6ed"
cyan = "#48b0bd"
green = "#8ebd6b"
magenta = "#bf68d9"
red = "#e55561"
white = "#a0a8b7"
yellow = "#e2b86b"

[colors.bright]
black = "#535965"
blue = "#4fa6ed"
cyan = "#48b0bd"
green = "#8ebd6b"
magenta = "#bf68d9"
red = "#e55561"
white = "#a0a8b7"
yellow = "#e2b86b"
